### ISSUE TITLE
License of derivative work

### ISSUE THREAD

**Issue by GPSnoopy** [GoncaloFDS/Lift#1]
Hi,

Browsing the interface and source code, it's quite clear this is a derivative work from https://github.com/GPSnoopy/RayTracingInVulkan. The license is quite permissive but is very explicit about the original copyright. In particular:

```
BSD 3-Clause License

Copyright (c) 2019, Tanguy Fautré
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

[...]
```

It would be the right thing to keep the original LICENSE file and explicitly state this is a derivative work in the README file

I would also suggest listing in the README file the modifications that were made, such that you can give credit where credit is due to your original work and research. I'll be sure to look into the OptiX integration, as this is quite an interesting feature.

Looking forward to the thesis. Best of luck! 

Regards,
Tanguy

**Comment by GoncaloFDS** [comment]
I will! I wasn't sure how to do this and your work was obviously a big influence and the base of mine. Thank you. Where should I put the license?

**Comment by GPSnoopy** [comment]
Hi @GoncaloFDS,

No worries. It's actually positive to see it being used by other people. That's the whole reason for it being open source in the first place. I noticed your work via Peter Shirley's tweet.

From what I've seen, it's quite common to have a single LICENSE file in the root of your project with your own copyright and license, followed by the copyrights and licenses of the original material.

For example (look at the TensorFlow or Boost references):
https://github.com/apache/arrow/blob/master/LICENSE.txt

Having a mention in the README of your references and inspirations is not legally necessary, but good etiquette since it's far more visible.

**Comment by GoncaloFDS** [comment]
Awesome I'll do that. If you give me your twitter handle I'll also tag you on my next post if you'd like :) I tried looking for GPSnoopy on the first one but I didn't find you.

**Comment by GPSnoopy** [comment]
Amazingly, I don't have a Twitter account 😄 
But I appreciate the gesture

**Comment by GoncaloFDS** [comment]
I've added the license and updated the Readme. 
Please check if you are ok with the changes.

**Comment by GPSnoopy** [comment]
Looks good. Thank you 😃
