### ISSUE TITLE
VkAccelerationStructureCreateGeometryTypeInfoKHR is undefined

### ISSUE THREAD

**Issue by darrenc182** [GoncaloFDS/Lift#18]
VkAccelerationStructureCreateGeometryTypeInfoKHR is undefined due to the change to standardize  the Vulkan Raytracing implementation by the Khronos Group.

**Comment by GoncaloFDS** [comment]
Hi @darrenc182
a "small" refactor is needed to support the standardization of the Vulkan RT API, I'm not sure when I'll be able to address this 😢

**Comment by GoncaloFDS** [comment]
@darrenc182 I finally had the time to make the port.

**Comment by darrenc182** [comment]
Thanks for the update.  I will have a look.
